Initial commit of the PHP server quickstart
twilio/voice-quickstart-server-php pull request #1
Opened 2018-01-27 02:26 UTC by bchen-twilio

2018-01-29 20:53 UTC, bchen-twilio commented on accessToken.php
> +$identity = isset($_GET["identity"]) ? $_GET["identity"] : "identity";
By default PHP supports both `GET` and `POST` without any specifier in the source. We are assuming the request is coming in as `GET` but we want all the endpoints to support both methods.

2018-01-30 02:31 UTC, idelgado requested changes

2018-01-30 02:31 UTC, idelgado commented on placeCall.php
> +$call = $client->calls->create(
Some functionality is missing. See Python PR.

2018-01-30 02:31 UTC, idelgado commented on makeCall.php
> +} else if (is_numeric($to)) {
You need to replace `+` character with `` and then check for is_numeric unless `is_numeric` ignores `+` characters. I'll add a test for this.

2018-01-30 02:38 UTC, idelgado commented on makeCall.php
> +if (empty($to) || !isset($to)) {
Usually you want to check for isset before you check for empty. Is that true for PHP?

2018-01-30 02:38 UTC, idelgado commented on makeCall.php
> +if (empty($to) || !isset($to)) {
Same here.

2018-01-30 03:08 UTC, idelgado requested changes

2018-01-30 03:08 UTC, idelgado commented on makeCall.php
> +} else if (is_numeric(str_replace('', '+', $to))) {
should be `str_replace('+', '', $to)`

2018-01-30 03:08 UTC, idelgado commented on placeCall.php
> +} else if (is_numeric(str_replace('', '+', $to))) {
Same here.

2018-01-30 03:08 UTC, idelgado commented on placeCall.php
> +} else if (is_numeric(str_replace('', '+', $to))) {
http://php.net/manual/en/function.str-replace.php

2018-01-30 03:39 UTC, idelgado requested changes

2018-01-30 03:39 UTC, idelgado commented on placeCall.php
> +$to = isset($_GET["to"]) ? $_GET["to"] : NULL;
Support for POST is missing

2018-01-30 04:33 UTC, idelgado approved these changes

2018-01-30 07:46 UTC, merged